---
tcp:
  target: "localhost:8080"
  port: ":8020"

http_routes:
  - target: "http://host.docker.internal:8081"
    host: "localhost"

  - target: "http://httpbin:80"
    host: "test.localhost"
    path_prefix: "/"

http_config:
  port: ":8021"
  shutdown_timeout: "5s"

log_level: "log"
