---
http_routes:
  - target: "https://jsonplaceholder.typicode.com"
    host: "localhost"
    path_prefix: "/https"
    strip_path_prefix: true

  - target: "http://host.docker.internal:8081"
    host: "localhost"

  - target: "http://httpbin:80"
    host: "test.localhost"
    path_prefix: "/"

http_config:
  port: ":8021"
  shutdown_timeout: "5s"

log_level: "log"
