services:
  reverse-proxy:
    build:
      context: .
    container_name: go-reverse-proxy
    environment:
      - CONFIG_FILE=${CONFIG_FILE:-config/config-docker.yml}
      - INTERNAL_API_PORT=${INTERNAL_API_PORT:-:42007}
    volumes:
      - ./config:/build/config
    networks:
        - local
    ports:
      - 42007:42007
      - 8020:8020
      - 8021:8021
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - local
    ports:
      - 9090:9090
networks:
  local:
    driver: bridge
