---
http_routes:
  - target: "https://jsonplaceholder.typicode.com"
    host: "localhost"
    path_prefix: "/https"
    strip_path_prefix: true

  - target: "http://localhost:8081"
    host: "localhost"

  - target: "http://localhost:8082"
    host: "admin.localhost"
    path_prefix: "/payments"

  - target: "http://localhost:8083"
    host: "admin.localhost"
    path_prefix: "/users"

  - target: "http://localhost:8085"
    host: "admin.localhost"
    path_prefix: "/long"

  - target: "http://localhost:8084"
    host: "admin.localhost"
    path_prefix: "/"

http_config:
  port: ":8021"
  shutdown_timeout: "5s"

log_level: "debug"
