# my global config
global:
  scrape_interval: 15s 
  evaluation_interval: 15s

scrape_configs:
  - job_name: "reverse_proxy"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["reverse-proxy:42007"]
