---
tcp:
  target: "localhost:8080"
  port: ":8020"

http_routes:
  - target: "http://host.docker.internal:8081"
    host: "localhost"

  - target: "http://host.docker.internal:8082"
    host: "admin.localhost"
    path_prefix: "/payments"

  - target: "http://host.docker.internal:8083"
    host: "admin.localhost"
    path_prefix: "/users"

  - target: "http://host.docker.internal:8085"
    host: "admin.localhost"
    path_prefix: "/long"

  - target: "http://host.docker.internal:8084"
    host: "admin.localhost"
    path_prefix: "/"

http_config:
  port: ":8021"
  shutdown_timeout: "5s"

log_level: "debug"
